### ISSUE TITLE
Rule to allow/disallow empty line after a group of properties

### ISSUE THREAD

**Issue by xBau** [cahamilton/stylelint-config-property-sort-order-smacss#12]
Would be nice to have a rule to be able to allow/disallow an empty line after any group of properties. 

```css
body {
  width: auto;
  height: 100%;
  margin: 0;

  background: #FFF;

  color: #000;
  font: 100%/1.5 'Courier New', Courier, monospace;
  font-weight: 400;
}
```

This rule only would make sense for this smacss config in my opinion.
